config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'profile', to: 'pages#profile'
  get 'competences', to: 'pages#competences'
  get 'experiences', to: 'pages#experiences'
  get 'portfolio', to: 'pages#portfolio'
  get 'contact', to: 'pages#contact'

  get 'front_end', to: 'projects#front_end'
  get 'full_stack', to: 'projects#full_stack'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/front_end.rb
class FrontEnd < ApplicationRecord
end

app/models/preference.rb
class Preference < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :set_theme

  def set_theme
    if params[:theme].present?
      theme = params[:theme].to_sym
      # session[:theme] = theme
      cookies[:theme] = theme
      redirect_to(request.referrer || root_path)
    end
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!

  def home
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  skip_before_action :authenticate_user!

  def front_end
  end

  def full_stack
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kevin Kotcherga - Développeur Web - Ruby On Rails - React - Full stack</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <%= favicon_link_tag %>
  </head>


  <body id="<%= controller.controller_name %>-<%= controller.action_name %>">
    <section >
      <div class="container">

        <%= render 'shared/header' %>
        <%= render 'shared/navbar' %>
        <%= render 'shared/switch_dark_mode' %>

        <%= yield %>
    </section>
  </body>
</html>

app/views/pages/contact.html.erb
<div class="container-card__contact">
  <div class="card__contact">
    <div class="content-card__contact">
      <div class="section-contact__container">
        <form class="section-contact__container-formulaire" action="../php/sendEmail.php" method="post">
          <h3>Merci de prendre le temps de me contacter</h3>
            <h4>Laissez moi un message et j'y répondrai le plus rapidement possible :</h4>
              <fieldset>
                <input class="section-contact__container-formulaire-name" name='nom' placeholder="Nom" type="text" tabindex="1" required autofocus>
              </fieldset>
              <fieldset>
                <input class="section-contact__container-formulaire-email" name='email' placeholder="Email" type="email" tabindex="2" required>
              </fieldset>
              <fieldset>
                <textarea class="section-contact__container-formulaire-message" name='message' placeholder="Message" tabindex="3" required></textarea>
              </fieldset>
              <fieldset>
                <button id="contact-submit" name="submit" type="submit" data-submit="...Sending">Envoyer votre message</button>
              </fieldset>
        </form>
      </div>
    </div>
  </div>
</div>

<!-- MOVING IMAGES -->

  <div class="imgDoodle10">
    <%= image_tag ("object11.png") %>
  </div>

  <div class="imgDoodle11">
    <%= image_tag ("object11.png") %>
  </div>
</div>

app/views/pages/experiences.html.erb
<div class="container-card__experience">
  <div class="card__experience">
    <div class="content-card__experience">
      <h3>Expériences Professionnelles :</h3>
        <p><span class="titre">Magasinier - CDI</span> </br> (28/08/19 - 31/03/21) </p>
        <p><span class="titre">Ingénieur du son - Auto-entrepeneur</span> </br> (02/06/20 - 01/11/20)</p>
        <p><span class="titre">Projet Muscial - Auto-entrepeneur</span> </br> (02/09/18 - 01/06/20)</p>
        <p><span class="titre">Menuisier Bois - Alternance</span> </br> (01/09/16 - 01/09/18) </p>
        <p><span class="titre">Réceptionniste d'hôtel / Serveur en restauration</span>  (01/09/14 - 31/08/16)</p>
    </div>
  </div>

  <div class="card__experience">
    <div class="content-card__experience">
      <h3>Diplômes :</h3>
      <p><span class="titre">OpenClassrooms (2021) :</span> Etude d'html, css, php, javascript, git et gitHub, sass.</p>
      <p><span class="titre">La Machine à Mixer (2019/2020) :</span> Formation MIX 101, MIX Mastercass, Mastering.</p>
      <p><span class="titre">BTP CFA de l’Hérault (11/07/2018) :</span> Menuisier fabricant de menuiserie, mobilier et agencement.</p>
      <p><span class="titre">H&C conseil  (31/08/15) :</span> Serveur en restauration option sommellerie.</p>
      <p><span class="titre">Lycée Louis Feuillade (01/07/14) :</span> Baccalauréat Sciences et technologies du management et de la gestion.</p>
    </div>
  </div>
</div>

<script type="text/javascript" src="../vanilla-tilt.js"></script>
  <script>
    VanillaTilt.init(document.querySelectorAll(".card__experience"),{
    max: 5,
    speed: 1000,
    glare: true,
    "max-glare": 1,
    });
  </script>

  <!-- MOVING IMAGES -->

  <div class="imgDoodle5">
    <%= image_tag ("object7.png") %>
  </div>

  <div class="imgDoodle6">
    <%= image_tag ("object6.png") %>
  </div>

  <div class="imgDoodle7">
    <%= image_tag ("object6.png") %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="content">
  <h2>Bienvenue</h2>
  <p>Je suis un développeur web full stack utilisant ruby on rails, javascript, html, css et php. N'hésitez pas à jeter un œil à mes derniers projets dans la section portfolio.</p>

  <%= link_to "Portfolio", portfolio_path %>
</div>

<div class="imgBx">
  <%= image_tag ("Saly-38.png") %>
</div>

app/views/pages/portfolio.html.erb
<div class="container-card__portfolio">

<%= link_to front_end_path, class: "link-to" do %>
  <div class="card__portfolio_main">
    <div class="content-card__portfolio">
      <figure>
        <%= image_tag ("other_03.png"), class: "img-portfolio_main" %>
            <figcaption>Front End</figcaption>
        </figure>
    </div>
  </div>
<% end %>
<%= link_to full_stack_path, class: "link-to" do %>
  <div class="card__portfolio_main">
    <div class="content-card__portfolio">
        <figure>
          <%= image_tag ("other_11.png"), class: "img-portfolio_main" %>
            <figcaption>Full Stack</figcaption>
        </figure>
    </div>
  </div>
<% end %>

</div>

<!-- MOVING IMAGES -->

<div class="imgDoodle5">
  <%= image_tag ("object7.png") %>
</div>

<div class="imgDoodle6">
  <%= image_tag ("object6.png") %>
</div>

<div class="imgDoodle7">
  <%= image_tag ("object6.png") %>
</div>

<script type="text/javascript" src="vanilla-tilt.js"></script>
<script>
  VanillaTilt.init(document.querySelectorAll(".card__portfolio_main"),{
  max: 15,
  speed: 1000,
  glare: false,
  "max-glare": 1,
  });
</script>

app/views/pages/profile.html.erb
<div class="container-profil">
  <div class="container-profil__text">
    <h1>Hello je m'appelle Kevin 👋</h1>
    <p>Je suis un développeur full stack ruby on rails passionné.</p>
    <p>Je travaille avec les langages :</p>
      <ul>
        <li>Ruby et Ruby on Rails.</li>
        <li>⚡ Stimulus et React.</li>
        <li>CSS, Bootstrap et Figma pour le design.</li>
      </ul>
    <p>Je lis actuellement le livre: "Ruby on Rails Tutorial by Michael Hartl" pour améliorer mes skills en ruby.</p>
    <p>Je travaille à la réalisation d'un clone twitter avec ruby on rails.</p>
    <p>Je réalise un maximum de projets différents (visible sur mon portfolio) pour m'améliorer en rails et react.</p>
  </div>
</div>

  <!-- MOVING IMAGE-->

  <div class="imgDoodle">
    <%= image_tag ("object.png") %>
  </div>

  <div class="imgDoodle2">
    <%= image_tag ("object2.png") %>
  </div>

</div>

app/views/projects/front_end.html.erb
<div class="container-card__portfolio">

<%= link_to 'https://kevinkotcherga.github.io/clothing_site/', class: "link-to" do %>
  <div class="card__portfolio">
    <div class="content-card__portfolio">
        <figure>
          <%= image_tag ("project9-mode.jpg"), class: "img-portfolio" %>
            <figcaption>Site mode</figcaption>
        </figure>
    </div>
  </div>
<% end %>

<%= link_to 'https://kevinkotcherga.github.io/zoom/', class: "link-to" do %>
  <div class="card__portfolio">
    <div class="content-card__portfolio">
        <figure>
        <%= image_tag ("project8-zoom.jpg"), class: "img-portfolio" %>
            <figcaption>Zoom</figcaption>
        </figure>
    </div>
  </div>
<% end %>

<%= link_to 'https://kevinkotcherga.github.io/quiz/', class: "link-to" do %>
  <div class="card__portfolio">
    <div class="content-card__portfolio">
        <figure>
          <%= image_tag ("project7-quiz.jpg"), class: "img-portfolio" %>
            <figcaption>Quiz</figcaption>
        </figure>
    </div>
  </div>
<% end %>

<%= link_to 'https://kevinkotcherga.github.io/pop-up/', class: "link-to" do %>
  <div class="card__portfolio">
    <div class="content-card__portfolio">
        <figure>
          <%= image_tag ("project2-popup.jpg"), class: "img-portfolio" %>
            <figcaption>Pop-up</figcaption>
        </figure>
    </div>
  </div>
<% end %>

<%= link_to 'https://kevinkotcherga.github.io/notification/', class: "link-to" do %>
  <div class="card__portfolio">
    <div class="content-card__portfolio">
        <figure>
          <%= image_tag ("project4-notification.jpg"), class: "img-portfolio" %>
            <figcaption>Notifications</figcaption>
        </figure>
    </div>
  </div>
<% end %>

<%= link_to 'https://kevinkotcherga.github.io/auto_text/', class: "link-to" do %>
  <div class="card__portfolio">
    <div class="content-card__portfolio">
      <figure>
        <%= image_tag ("project1-auto-text.jpg"), class: "img-portfolio" %>
            <figcaption>Auto text</figcaption>
      </figure>
    </div>
  </div>
<% end %>


<%= link_to 'https://kevinkotcherga.github.io/hamburger_menu/', class: "link-to" do %>
  <div class="card__portfolio">
    <div class="content-card__portfolio">
        <figure>
          <%= image_tag ("project3-btnmenu.jpg"), class: "img-portfolio" %>
            <figcaption>Menu latéral</figcaption>
        </figure>
    </div>
  </div>
<% end %>


<%= link_to 'https://kevinkotcherga.github.io/dark_mode/', class: "link-to" do %>
  <div class="card__portfolio">
    <div class="content-card__portfolio">
        <figure>
          <%= image_tag ("project5-darkmode.jpg"), class: "img-portfolio" %>
            <figcaption>Dark mode</figcaption>
        </figure>
    </div>
  </div>
<% end %>




</div>

<!-- MOVING IMAGES -->

<div class="imgDoodle5">
  <%= image_tag ("object7.png") %>
</div>

<div class="imgDoodle6">
  <%= image_tag ("object6.png") %>
</div>

<div class="imgDoodle7">
  <%= image_tag ("object6.png") %>
</div>

<script type="text/javascript" src="vanilla-tilt.js"></script>
<script>
  VanillaTilt.init(document.querySelectorAll(".card__portfolio"),{
  max: 15,
  speed: 1000,
  glare: false,
  "max-glare": 1,
  });
</script>

app/views/projects/full_stack.html.erb
<div class="container-card__portfolio">

  <%= link_to 'https://ovninb-juleschevrant.herokuapp.com/', class: "link-to" do %>
    <div class="card__portfolio">
      <div class="content-card__portfolio">
          <figure>
            <%= image_tag ("ovninb.png"), class: "img-portfolio" %>
              <figcaption>Clone Airbnb (Ovni'nb)</figcaption>
          </figure>
      </div>
    </div>
  <% end %>

</div>

<!-- MOVING IMAGES -->

<div class="imgDoodle5">
  <%= image_tag ("object7.png") %>
</div>

<div class="imgDoodle6">
  <%= image_tag ("object6.png") %>
</div>

<div class="imgDoodle7">
  <%= image_tag ("object6.png") %>
</div>

<script type="text/javascript" src="vanilla-tilt.js"></script>
<script>
  VanillaTilt.init(document.querySelectorAll(".card__portfolio"),{
  max: 15,
  speed: 1000,
  glare: false,
  "max-glare": 1,
  });
</script>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_header.html.erb
<header class="header">
  <div class="header__titre-principale">
    <div class="header__titre-principale-nom">
      <h1>Kevin Kotcherga</h1>
    </div>
    <p class="header__titre-principale-desciption"><span>Développeur Full Stack</span></p>
  </div>

  <nav class="nav">
    <ul class="nav__ul">
      <li class="<%= "active" if controller.controller_name == "pages" && controller.action_name == "home" %>"><%= link_to "Accueil", root_path %></li>
      <li class="<%= "active" if controller.controller_name == "pages" && controller.action_name == "profile" %>"><%= link_to "Profile", profile_path %></li>
      <li class="<%= "active" if controller.controller_name == "pages" && controller.action_name == "competences" %>"><%= link_to "Compétences", competences_path %></li>
      <li class="<%= "active" if controller.controller_name == "pages" && controller.action_name == "portfolio" || (controller.controller_name == "projects" && controller.action_name == "front_end") || (controller.controller_name == "projects" && controller.action_name == "full_stack") %>"><%= link_to "Portfolio", portfolio_path %></li>
      <li class="<%= "active" if controller.controller_name == "pages" && controller.action_name == "contact" %>"><%= link_to "Contact", contact_path %></li>
    </ul>
  </nav>
</header>

app/views/shared/_navbar.html.erb
<ul class="nav-bar">
  <li>
    <a href="https://www.linkedin.com/in/kevinkotcherga/" target="_blank"><svg viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg" class="nav-bar__logos"><path d="m256 0c-141.363281 0-256 114.636719-256 256s114.636719 256 256 256 256-114.636719 256-256-114.636719-256-256-256zm-74.390625 387h-62.347656v-187.574219h62.347656zm-31.171875-213.1875h-.40625c-20.921875 0-34.453125-14.402344-34.453125-32.402344 0-18.40625 13.945313-32.410156 35.273437-32.410156 21.328126 0 34.453126 14.003906 34.859376 32.410156 0 18-13.53125 32.402344-35.273438 32.402344zm255.984375 213.1875h-62.339844v-100.347656c0-25.21875-9.027343-42.417969-31.585937-42.417969-17.222656 0-27.480469 11.601563-31.988282 22.800781-1.648437 4.007813-2.050781 9.609375-2.050781 15.214844v104.75h-62.34375s.816407-169.976562 0-187.574219h62.34375v26.558594c8.285157-12.78125 23.109375-30.960937 56.1875-30.960937 41.019531 0 71.777344 26.808593 71.777344 84.421874zm0 0"/></svg></a>
  </li>
  <li>
    <a href="https://github.com/kevinkotcherga" target="_blank"><svg viewBox="0 0 512 512" xmlns="http://www.w3.org/2000/svg" class="nav-bar__logos"><path d="m256 0c-140.609375 0-256 115.390625-256 256 0 119.988281 84.195312 228.984375 196 256v-84.695312c-11.078125 2.425781-21.273438 2.496093-32.550781-.828126-15.128907-4.464843-27.421875-14.542968-36.546875-29.910156-5.816406-9.8125-16.125-20.453125-26.878906-19.671875l-2.636719-29.882812c23.253906-1.992188 43.371093 14.167969 55.3125 34.230469 5.304687 8.921874 11.410156 14.152343 19.246093 16.464843 7.574219 2.230469 15.707032 1.160157 25.183594-2.1875 2.378906-18.972656 11.070313-26.074219 17.636719-36.074219v-.015624c-66.679687-9.945313-93.253906-45.320313-103.800781-73.242188-13.976563-37.074219-6.476563-83.390625 18.238281-112.660156.480469-.570313 1.347656-2.0625 1.011719-3.105469-11.332032-34.230469 2.476562-62.546875 2.984375-65.550781 13.078125 3.867187 15.203125-3.890625 56.808593 21.386718l7.191407 4.320313c3.007812 1.792969 2.0625.769531 5.070312.542969 17.371094-4.71875 35.683594-7.324219 53.726563-7.558594 18.179687.234375 36.375 2.839844 54.464844 7.75l2.328124.234375c-.203124-.03125.632813-.148437 2.035157-.984375 51.972656-31.480469 50.105469-21.191406 64.042969-25.722656.503906 3.007812 14.128906 31.785156 2.917968 65.582031-1.511718 4.65625 45.058594 47.300781 19.246094 115.753906-10.546875 27.933594-37.117188 63.308594-103.796875 73.253907v.015624c8.546875 13.027344 18.816406 19.957032 18.761719 46.832032v105.722656c111.808594-27.015625 196-136.011719 196-256 .003906-140.609375-115.386719-256-255.996094-256zm0 0"/></svg></a>
  </li>
  <li>
    <a href="CV-Kevin-Kotcherga.pdf" download="CV-kevin-kotcherga.pdf" target="_blank"><svg class="nav-bar__logos" xmlns="http://www.w3.org/2000/svg" height="48px" viewBox="0 0 24 24" width="48px" fill="#000000"><path d="M0 0h24v24H0V0z" fill="none"/><path d="M19 3h-4.18C14.4 1.84 13.3 1 12 1s-2.4.84-2.82 2H5c-1.1 0-2 .9-2 2v14c0 1.1.9 2 2 2h14c1.1 0 2-.9 2-2V5c0-1.1-.9-2-2-2zm-7-.25c.22 0 .41.1.55.25.12.13.2.31.2.5 0 .41-.34.75-.75.75s-.75-.34-.75-.75c0-.19.08-.37.2-.5.14-.15.33-.25.55-.25zM19 19H5V5h14v14zM12 6c-1.65 0-3 1.35-3 3s1.35 3 3 3 3-1.35 3-3-1.35-3-3-3zm0 4c-.55 0-1-.45-1-1s.45-1 1-1 1 .45 1 1-.45 1-1 1zm-6 6.47V18h12v-1.53c0-2.5-3.97-3.58-6-3.58s-6 1.07-6 3.58zM8.31 16c.69-.56 2.38-1.12 3.69-1.12s3.01.56 3.69 1.12H8.31z"/></svg></a>
  </li>
</ul>

app/views/shared/_switch_dark_mode.html.erb
<label class="switch">
  <input type="checkbox" id="checkBox" >
  <span class="slider"></span>
  <span class="on"><svg viewBox="0 0 24 24" color="text" width="24px" xmlns="http://www.w3.org/2000/svg" class="svg_on"><path d="M5.66 4.2L6.05 4.59C6.44 4.97 6.44 5.61 6.05 5.99L6.04 6C5.65 6.39 5.03 6.39 4.64 6L4.25 5.61C3.86 5.23 3.86 4.6 4.25 4.21L4.26 4.2C4.64 3.82 5.27 3.81 5.66 4.2Z"></path><path d="M1.99 10.95H3.01C3.56 10.95 4 11.39 4 11.95V11.96C4 12.51 3.56 12.95 3 12.94H1.99C1.44 12.94 1 12.5 1 11.95V11.94C1 11.39 1.44 10.95 1.99 10.95Z"></path><path d="M12 1H12.01C12.56 1 13 1.44 13 1.99V2.96C13 3.51 12.56 3.95 12 3.94H11.99C11.44 3.94 11 3.5 11 2.95V1.99C11 1.44 11.44 1 12 1Z"></path><path d="M18.34 4.2C18.73 3.82 19.36 3.82 19.75 4.21C20.14 4.6 20.14 5.22 19.75 5.61L19.36 6C18.98 6.39 18.35 6.39 17.96 6L17.95 5.99C17.56 5.61 17.56 4.98 17.95 4.59L18.34 4.2Z"></path><path d="M18.33 19.7L17.94 19.31C17.55 18.92 17.55 18.3 17.95 17.9C18.33 17.52 18.96 17.51 19.35 17.9L19.74 18.29C20.13 18.68 20.13 19.31 19.74 19.7C19.35 20.09 18.72 20.09 18.33 19.7Z"></path><path d="M20 11.95V11.94C20 11.39 20.44 10.95 20.99 10.95H22C22.55 10.95 22.99 11.39 22.99 11.94V11.95C22.99 12.5 22.55 12.94 22 12.94H20.99C20.44 12.94 20 12.5 20 11.95Z"></path><path fill-rule="evenodd" clip-rule="evenodd" d="M6 11.95C6 8.64 8.69 5.95 12 5.95C15.31 5.95 18 8.64 18 11.95C18 15.26 15.31 17.95 12 17.95C8.69 17.95 6 15.26 6 11.95ZM12 16C14.2091 16 16 14.2091 16 12C16 9.79086 14.2091 8 12 8C9.79086 8 8 9.79086 8 12C8 14.2091 9.79086 16 12 16Z"></path><path d="M12 22.9H11.99C11.44 22.9 11 22.46 11 21.91V20.95C11 20.4 11.44 19.96 11.99 19.96H12C12.55 19.96 12.99 20.4 12.99 20.95V21.91C12.99 22.46 12.55 22.9 12 22.9Z"></path><path d="M5.66 19.69C5.27 20.08 4.64 20.08 4.25 19.69C3.86 19.3 3.86 18.68 4.24 18.28L4.63 17.89C5.02 17.5 5.65 17.5 6.04 17.89L6.05 17.9C6.43 18.28 6.44 18.91 6.05 19.3L5.66 19.69Z"></path></svg></span>
  <span class="off"><svg viewBox="0 0 24 24" color="text" width="24px" xmlns="http://www.w3.org/2000/svg" class="svg_off"><path fill-rule="evenodd" clip-rule="evenodd" d="M4.1534 13.6089L4.15362 13.61C4.77322 16.8113 7.42207 19.3677 10.647 19.8853L10.6502 19.8858C13.0412 20.2736 15.2625 19.6103 16.9422 18.2833C11.3549 16.2878 7.9748 10.3524 9.26266 4.48816C5.69846 5.77194 3.35817 9.51245 4.1534 13.6089ZM10.0083 2.21054C4.76622 3.2533 1.09895 8.36947 2.19006 13.9901C2.97006 18.0201 6.28006 21.2101 10.3301 21.8601C13.8512 22.4311 17.0955 21.1608 19.2662 18.8587C19.2765 18.8478 19.2866 18.837 19.2968 18.8261C19.4385 18.6745 19.5757 18.5184 19.7079 18.3581C19.7105 18.355 19.713 18.3519 19.7156 18.3487C19.8853 18.1426 20.0469 17.9295 20.2001 17.7101C20.4101 17.4001 20.2401 16.9601 19.8701 16.9201C19.5114 16.8796 19.1602 16.8209 18.817 16.7452C18.7964 16.7406 18.7758 16.736 18.7552 16.7313C18.6676 16.7114 18.5804 16.6903 18.4938 16.6681C18.4919 16.6676 18.4901 16.6672 18.4882 16.6667C13.0234 15.2647 9.72516 9.48006 11.4542 4.03417C11.4549 4.03214 11.4555 4.03012 11.4562 4.0281C11.4875 3.92954 11.5205 3.83109 11.5552 3.73278C11.5565 3.72911 11.5578 3.72543 11.5591 3.72175C11.6768 3.38921 11.8136 3.05829 11.9701 2.73005C12.1301 2.39005 11.8501 2.01005 11.4701 2.03005C11.1954 2.04379 10.924 2.06848 10.6561 2.10368C10.6517 2.10427 10.6472 2.10486 10.6428 2.10545C10.4413 2.13221 10.2418 2.16492 10.0446 2.2034C10.0325 2.20576 10.0204 2.20814 10.0083 2.21054Z"></path></svg></span>
</label>